apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::167819473967:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-8Z5DlJDjQzdL
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::167819473967:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-04T07:10:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1168"
  uid: 0723923e-9cd1-4897-831b-73510a93ae5a

