apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::167819473967:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-WDnWU5T1LMxF
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::167819473967:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-02T10:44:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1226"
  uid: e4c4671e-1210-42a0-8b2b-5f926bc10245
